export const CLIENT_FORM_TEXT = {
  back: 'العودة للعملاء',
  title: 'إضافة عميل جديد',
  subtitle: 'أدخل بيانات العميل واربطه بالجهة المناسبة',
  name: 'اسم العميل',
  namePlaceholder: 'مثال: مصنع لبدة',
  nameRequired: 'اسم العميل مطلوب.',
  shortCode: 'الرمز المختصر',
  shortCodePlaceholder: 'مثال: LB',
  shortCodeRequired: 'الرمز المختصر مطلوب.',
  linkedClient: 'الجهة المرتبطة',
  linkedClientPlaceholder: 'اختر الجهة',
  linkedClientRequired: 'اختر الجهة المرتبطة بالعميل.',
  noClients: 'لا توجد جهات مسجلة. أضف جهة من صفحة الإعدادات أولاً.',
  loadClientsError: 'تعذر تحميل الجهات. حاول تحديث الصفحة.',
  save: 'حفظ العميل',
  saving: 'جارٍ الحفظ…',
  cancel: 'إلغاء',
  saved: 'تمت إضافة العميل بنجاح',
  createFailed: 'تعذر إضافة العميل. حاول مرة أخرى.',
} as const
