export const CLIENT_FORM_TEXT = {
  back: 'العودة للشركات والمصانع',
  title: 'إضافة مصنع',
  subtitle: 'اختر الشركة الأم ثم أدخل اسم المصنع والكود.',
  name: 'اسم المصنع',
  namePlaceholder: 'مثال: مصنع لبدة',
  nameRequired: 'اسم المصنع مطلوب.',
  shortCode: 'كود المصنع',
  shortCodePlaceholder: 'مثال: LB',
  shortCodeRequired: 'كود المصنع مطلوب.',
  linkedClient: 'الشركة الأم',
  linkedClientPlaceholder: 'اختر الشركة',
  linkedClientRequired: 'اختر الشركة الأم للمصنع.',
  noClients: 'لا توجد شركات مسجلة. أضف شركة أولاً من صفحة الشركات والمصانع.',
  loadClientsError: 'تعذر تحميل الشركات. حاول تحديث الصفحة.',
  save: 'حفظ المصنع',
  saving: 'جارٍ الحفظ…',
  cancel: 'إلغاء',
  saved: 'تمت إضافة المصنع بنجاح',
  createFailed: 'تعذر إضافة المصنع. حاول مرة أخرى.',
} as const
