export const HEADER_TEXT = {
  sidebarOpen: 'فتح القائمة الجانبية',
  sidebarClose: 'إغلاق القائمة الجانبية',
  breadcrumbs: 'مسار الصفحة',
  notifications: 'الإشعارات',
  notificationUnread: (count: number) => `الإشعارات، ${count} غير مقروء`,
  markAllRead: 'تحديد الكل كمقروء',
  noNotifications: 'لا توجد إشعارات جديدة',
  unreadIndicator: 'غير مقروء',
  account: 'الحساب',
  userMenu: 'قائمة المستخدم',
  theme: 'المظهر',
  themeLight: 'فاتح',
  themeDark: 'داكن',
  themeSystem: 'تلقائي',
  logout: 'تسجيل الخروج',
  home: 'الرئيسية',
  dashboard: 'لوحة المعلومات',
  userDashboard: 'لوحة معلومات المستخدم',
  managerDashboard: 'لوحة معلومات الفريق',
  adminDashboard: 'لوحة معلومات النظام',
  requisitions: 'طلبات الشراء',
  newRequisition: 'طلب جديد',
  requisitionDetail: 'تفاصيل الطلب',
  requisitionDetailWithNumber: (id: string) => `تفاصيل الطلب #${id}`,
  editRequisition: 'تعديل الطلب',
  printRequisition: 'طباعة الطلب',
  clients: 'العملاء',
  newClient: 'إضافة عميل جديد',
  users: 'المستخدمون',
  newUser: 'إضافة مستخدم جديد',
  editUser: 'تعديل المستخدم',
  settings: 'الإعدادات',
  workflow: 'تدفق العمل',
  page: 'الصفحة الحالية',
  initialFallback: 'م',
} as const
