export const USER_EDIT_FORM_TEXT = {
  back: 'العودة للمستخدمين',
  title: 'تعديل المستخدم',
  subtitle: 'تحديث دور المستخدم وحالة الحساب',
  identitySection: 'معلومات الحساب',
  identityDescription: 'اسم المستخدم المرتبط بهذا الحساب.',
  accessSection: 'الدور وحالة الحساب',
  accessDescription: 'إدارة صلاحيات المستخدم وحالة الحساب ومديره المسؤول.',
  username: 'اسم المستخدم',
  role: 'الدور',
  manager: 'المدير المسؤول',
  managerPlaceholder: 'اختر المدير المسؤول',
  managerLoading: 'جارٍ تحميل المديرين…',
  managerUnassigned: 'بدون مدير مسؤول',
  managerHint: 'سيتمكن المدير المحدد من مراجعة طلبات هذا المستخدم.',
  managerLoadFailed: 'تعذر تحميل قائمة المديرين.',
  managerRetry: 'إعادة المحاولة',
  managerNoneAvailable: 'لا يوجد مديرون نشطون. أنشئ حساب مدير أولاً.',
  active: 'حالة الحساب',
  activeOn: 'حساب نشط',
  activeOff: 'حساب غير نشط',
  inactiveHint: 'الحسابات غير النشطة لا يمكنها تسجيل الدخول.',
  roles: {
    Admin: {
      label: 'مسؤول النظام',
      description: 'صلاحية كاملة لإدارة النظام وإعداداته.',
    },
    Manager: {
      label: 'مدير',
      description: 'يمكنه إدارة الفريق والبيانات المشتركة.',
    },
    User: {
      label: 'مستخدم قياسي',
      description: 'يمكنه عرض عمله وتعديله.',
    },
  },
  roleRequired: 'اختر دوراً للمستخدم.',
  activeRequired: 'حدد حالة الحساب.',
  loadFailed: 'تعذر تحميل بيانات المستخدم.',
  save: 'حفظ التعديلات',
  saving: 'جارٍ الحفظ…',
  cancel: 'إلغاء',
  saved: 'تم تعديل المستخدم بنجاح',
  saveFailed: 'تعذر حفظ التغييرات. حاول مرة أخرى.',
} as const
