export const USER_FORM_TEXT = {
  back: 'العودة للمستخدمين',
  title: 'إضافة مستخدم جديد',
  subtitle: 'إنشاء حساب دخول جديد مع صلاحية دور محدد',
  credentialsSection: 'بيانات الدخول',
  credentialsDescription: 'حدد اسم المستخدم وكلمة المرور للحساب الجديد.',
  accessSection: 'الدور وحالة الحساب',
  accessDescription: 'اختر الصلاحيات وحدد ما إذا كان الحساب نشطاً.',
  username: 'اسم المستخدم',
  usernamePlaceholder: 'username',
  usernameHint: 'استخدم أحرفاً إنجليزية أو أرقاماً أو نقطة أو شرطة سفلية فقط.',
  checklistMet: 'مستوفى: ',
  checklistNeeded: 'مطلوب: ',
  usernameRequired: 'اسم المستخدم مطلوب.',
  usernameFormat: 'استخدم الأحرف الإنجليزية والأرقام والنقطة والشرطة السفلية فقط.',
  password: 'كلمة المرور',
  passwordPlaceholder: '••••••••',
  passwordHint: 'استخدم 8 أحرف على الأقل، مع حرف واحد ورقم واحد.',
  passwordRequired: 'كلمة المرور مطلوبة.',
  passwordLength: 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل.',
  passwordLetter: 'أضف حرفاً واحداً على الأقل.',
  passwordNumber: 'أضف رقماً واحداً على الأقل.',
  showPassword: 'إظهار كلمة المرور',
  hidePassword: 'إخفاء كلمة المرور',
  passwordChecks: {
    length: '8 أحرف على الأقل',
    letter: 'حرف واحد على الأقل',
    number: 'رقم واحد على الأقل',
  },
  role: 'الدور',
  manager: 'المدير المسؤول',
  managerPlaceholder: 'اختر المدير المسؤول',
  managerLoading: 'جارٍ تحميل المديرين…',
  managerUnassigned: 'بدون مدير مسؤول',
  managerHint: 'سيتمكن المدير المحدد من مراجعة طلبات هذا المستخدم.',
  managerLoadFailed: 'تعذر تحميل قائمة المديرين.',
  managerRetry: 'إعادة المحاولة',
  managerNoneAvailable: 'لا يوجد مديرون نشطون. أنشئ حساب مدير أولاً.',
  roles: {
    standard: {
      label: 'مستخدم قياسي',
      description: 'يمكنه عرض عمله وتعديله.',
    },
    admin: {
      label: 'مسؤول',
      description: 'يمكنه أيضاً إدارة الفريق والبيانات المشتركة.',
    },
    system_manager: {
      label: 'مدير النظام',
      description: 'صلاحية كاملة تشمل إعدادات النظام.',
    },
  },
  active: 'حالة الحساب',
  activeOn: 'حساب نشط',
  activeOff: 'حساب غير نشط',
  inactiveHint: 'الحسابات غير النشطة لا يمكنها تسجيل الدخول.',
  save: 'حفظ المستخدم',
  saving: 'جارٍ الحفظ…',
  cancel: 'إلغاء',
  saved: 'تم حفظ المستخدم',
  createFailed: 'تعذر حفظ المستخدم. حاول مرة أخرى.',
} as const
